## 데이터 가공

## 패키지 임포트

In [2]:
import pandas as pd
import numpy as np

In [21]:
# 데이터 셋 불러오기
meteor_showers = pd.read_csv('pyhon/data/meteorshowers.csv')
moon_phases = pd.read_csv('pyhon/data/moonphases.csv')
constellations = pd.read_csv('pyhon/data/constellations.csv')
cities = pd.read_csv('pyhon/data/cities.csv')

In [114]:
moon_phases = pd.read_csv('pyhon/data/moonphases.csv')

In [ ]:
meteor_showers.info()

In [15]:
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,april,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,may,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,october,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,august,july,14,august,24,northern,northern
4,Leonids,Leo,november,november,6,november,30,"northern, southern","northern, southern"

In [16]:
meteor_showers.head()

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,april,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,may,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,october,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,august,july,14,august,24,northern,northern
4,Leonids,Leo,november,november,6,november,30,"northern, southern","northern, southern"

In [17]:
# 월명을 숫자로 변환하기 위한 딕셔너리 생성 months
#meteor_showers.apply()
#meteor_showers.map()
#meteor_showers.replace()

months = {'january':1,'feburary':2,'march':3,'april':4,'may':5,'june':6,'july':7,'august':8,'september':9,'october':10,'november':11,'december':12}

In [22]:
# 월명을 숫자로 변환 map 활용
meteor_showers['bestmonth'] = meteor_showers['bestmonth'].map(months)
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,4,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,5,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,10,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,8,july,14,august,24,northern,northern
4,Leonids,Leo,11,november,6,november,30,"northern, southern","northern, southern"

In [23]:
meteor_showers['startmonth'] = meteor_showers['startmonth'].map(months)
meteor_showers['endmonth'] = meteor_showers['endmonth'].map(months)
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,4,4,21,4,22,northern,northern
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern"
3,Perseids,Perseus,8,7,14,8,24,northern,northern
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern"

In [115]:
moon_phases

        month  day      moonphase specialevent
0     january    1            NaN          NaN
1     january    2  first quarter          NaN
2     january    3            NaN          NaN
3     january    4            NaN          NaN
4     january    5            NaN          NaN
..        ...  ...            ...          ...
361  december   27            NaN          NaN
362  december   28            NaN          NaN
363  december   29      full moon          NaN
364  december   30            NaN          NaN
365  december   31            NaN          NaN

[366 rows x 4 columns]

In [116]:
moon_phases['month'] = moon_phases['month'].map(months)
#moon_phases['month'] = moon_phases['month'].replace(months)
moon_phases

     month  day      moonphase specialevent
0      1.0    1            NaN          NaN
1      1.0    2  first quarter          NaN
2      1.0    3            NaN          NaN
3      1.0    4            NaN          NaN
4      1.0    5            NaN          NaN
..     ...  ...            ...          ...
361   12.0   27            NaN          NaN
362   12.0   28            NaN          NaN
363   12.0   29      full moon          NaN
364   12.0   30            NaN          NaN
365   12.0   31            NaN          NaN

[366 rows x 4 columns]

In [27]:
constellations['bestmonth'] = constellations['bestmonth'].map(months)
constellations

  constellation  bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra          8             90          -40    21:00   northern
1      Aquarius         10             65          -90    21:00   southern
2         Orion          1             85          -75    21:00   northern
3       Perseus         12             90          -35    21:00   northern
4           Leo          4             90           65    21:00   northern

In [29]:
moon_phases.info()

<class 'pandas.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   month         337 non-null    float64
 1   day           366 non-null    int64
 2   moonphase     50 non-null     str
 3   specialevent  10 non-null     str
dtypes: float64(1), int64(1), str(2)
memory usage: 11.6 KB

In [30]:
constellations.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   constellation  5 non-null      str
 1   bestmonth      5 non-null      int64
 2   latitudestart  5 non-null      int64
 3   latitudeend    5 non-null      int64
 4   besttime       5 non-null      str
 5   hemisphere     5 non-null      str
dtypes: int64(3), str(3)
memory usage: 372.0 bytes

## 일자 정보 Datetime으로 변환(startdate 컬럼 생성)

In [46]:
#startdate 컬럼 추가


#meteor_showers -> 2020042

2020*10000 + meteor_showers['startmonth']*100 + meteor_showers['startday']

meteor_showers['startdate'] = pd.to_datetime(2020*10000 + meteor_showers['startmonth']*100 + meteor_showers['startday'],format='%Y%m%d')
#pd.to_datetime(2020*10000 + meteor_showers['startmonth']*100 + meteor_showers['startday'], format='%Y%m%d')

In [47]:
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere,startdate
0,Lyrids,Lyra,4,4,21,4,22,northern,northern,2020-04-21
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern,2020-04-19
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern",2020-10-02
3,Perseids,Perseus,8,7,14,8,24,northern,northern,2020-07-14
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern",2020-11-06

In [117]:
#meteor_showers['enddate'] = pd.to_datetime(2020*10000 + meteor_showers['endmonth']*100 + meteor_showers['endday'],format='%Y%m%d')
moon_phases['date'] = pd.to_datetime(2020*10000 + moon_phases['month']*100 + moon_phases['day'],format='%Y%m%d')

moon_phases

     month  day      moonphase specialevent       date
0      1.0    1            NaN          NaN 2020-01-01
1      1.0    2  first quarter          NaN 2020-01-02
2      1.0    3            NaN          NaN 2020-01-03
3      1.0    4            NaN          NaN 2020-01-04
4      1.0    5            NaN          NaN 2020-01-05
..     ...  ...            ...          ...        ...
361   12.0   27            NaN          NaN 2020-12-27
362   12.0   28            NaN          NaN 2020-12-28
363   12.0   29      full moon          NaN 2020-12-29
364   12.0   30            NaN          NaN 2020-12-30
365   12.0   31            NaN          NaN 2020-12-31

[366 rows x 5 columns]

In [51]:
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere,startdate,enddate
0,Lyrids,Lyra,4,4,21,4,22,northern,northern,2020-04-21,2020-04-22
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern,2020-04-19,2020-05-28
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern",2020-10-02,2020-11-07
3,Perseids,Perseus,8,7,14,8,24,northern,northern,2020-07-14,2020-08-24
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern",2020-11-06,2020-11-30

In [118]:
moon_phases

     month  day      moonphase specialevent       date
0      1.0    1            NaN          NaN 2020-01-01
1      1.0    2  first quarter          NaN 2020-01-02
2      1.0    3            NaN          NaN 2020-01-03
3      1.0    4            NaN          NaN 2020-01-04
4      1.0    5            NaN          NaN 2020-01-05
..     ...  ...            ...          ...        ...
361   12.0   27            NaN          NaN 2020-12-27
362   12.0   28            NaN          NaN 2020-12-28
363   12.0   29      full moon          NaN 2020-12-29
364   12.0   30            NaN          NaN 2020-12-30
365   12.0   31            NaN          NaN 2020-12-31

[366 rows x 5 columns]

In [119]:
# 달의 위상 데이터를 숫자로 변환

phases = {'new moon' : 0, 'first quarter':0.5,'third quarter':0.5,'full moon':1}

moon_phases['percentage'] = moon_phases['moonphase'].map(phases)

In [120]:
moon_phases

     month  day      moonphase specialevent       date  percentage
0      1.0    1            NaN          NaN 2020-01-01         NaN
1      1.0    2  first quarter          NaN 2020-01-02         0.5
2      1.0    3            NaN          NaN 2020-01-03         NaN
3      1.0    4            NaN          NaN 2020-01-04         NaN
4      1.0    5            NaN          NaN 2020-01-05         NaN
..     ...  ...            ...          ...        ...         ...
361   12.0   27            NaN          NaN 2020-12-27         NaN
362   12.0   28            NaN          NaN 2020-12-28         NaN
363   12.0   29      full moon          NaN 2020-12-29         1.0
364   12.0   30            NaN          NaN 2020-12-30         NaN
365   12.0   31            NaN          NaN 2020-12-31         NaN

[366 rows x 6 columns]

## 불필요한 컬럼 삭제

In [57]:
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere,startdate,enddate
0,Lyrids,Lyra,4,4,21,4,22,northern,northern,2020-04-21,2020-04-22
1,Eta Aquarids,Aquarius,5,4,19,5,28,"northern, southern",southern,2020-04-19,2020-05-28
2,Orionids,Orion,10,10,2,11,7,"northern, southern","northern, southern",2020-10-02,2020-11-07
3,Perseids,Perseus,8,7,14,8,24,northern,northern,2020-07-14,2020-08-24
4,Leonids,Leo,11,11,6,11,30,"northern, southern","northern, southern",2020-11-06,2020-11-30

In [ ]:
meteor_showers.drop(columns=['startmonth'], inplace=True)
meteor_showers.drop(columns=['startday'], inplace=True)
meteor_showers.drop(columns=['endmonth'], inplace=True)
meteor_showers.drop(columns=['endday'], inplace=True)
meteor_showers.drop(columns=['preferredhemisphere'],inplace=True)

In [76]:
meteor_showers.drop(columns=['preferredhemisphere'],inplace=True)

In [77]:
meteor_showers

           name   radiant  bestmonth          hemisphere  startdate    enddate
0        Lyrids      Lyra          4            northern 2020-04-21 2020-04-22
1  Eta Aquarids  Aquarius          5  northern, southern 2020-04-19 2020-05-28
2      Orionids     Orion         10  northern, southern 2020-10-02 2020-11-07
3      Perseids   Perseus          8            northern 2020-07-14 2020-08-24
4       Leonids       Leo         11  northern, southern 2020-11-06 2020-11-30

In [121]:
moon_phases.drop(columns=['month'],inplace=True)
moon_phases.drop(columns=['day'],inplace=True)

In [122]:
moon_phases

         moonphase specialevent       date  percentage
0              NaN          NaN 2020-01-01         NaN
1    first quarter          NaN 2020-01-02         0.5
2              NaN          NaN 2020-01-03         NaN
3              NaN          NaN 2020-01-04         NaN
4              NaN          NaN 2020-01-05         NaN
..             ...          ...        ...         ...
361            NaN          NaN 2020-12-27         NaN
362            NaN          NaN 2020-12-28         NaN
363      full moon          NaN 2020-12-29         1.0
364            NaN          NaN 2020-12-30         NaN
365            NaN          NaN 2020-12-31         NaN

[366 rows x 4 columns]

In [67]:
moon_phases['specialevent'].unique()

<StringArray>
[                         nan,            'super full moon',
             'micro new moon',    'penumbral lunar eclipse',
                 'black moon',            'micro full moon',
             'super new moon', 'blue moon, micro full moon']
Length: 8, dtype: str

In [123]:
moon_phases.drop(columns=['moonphase'],inplace=True)

In [124]:
moon_phases.drop(columns=['specialevent'],inplace=True)

In [125]:
moon_phases

          date  percentage
0   2020-01-01         NaN
1   2020-01-02         0.5
2   2020-01-03         NaN
3   2020-01-04         NaN
4   2020-01-05         NaN
..         ...         ...
361 2020-12-27         NaN
362 2020-12-28         NaN
363 2020-12-29         1.0
364 2020-12-30         NaN
365 2020-12-31         NaN

[366 rows x 2 columns]

In [72]:
constellations.drop(columns=['besttime'],inplace=True)

In [80]:
constellations

  constellation  bestmonth  latitudestart  latitudeend hemisphere
0          Lyra          8             90          -40   northern
1      Aquarius         10             65          -90   southern
2         Orion          1             85          -75   northern
3       Perseus         12             90          -35   northern
4           Leo          4             90           65   northern

In [79]:
meteor_showers

           name   radiant  bestmonth          hemisphere  startdate    enddate
0        Lyrids      Lyra          4            northern 2020-04-21 2020-04-22
1  Eta Aquarids  Aquarius          5  northern, southern 2020-04-19 2020-05-28
2      Orionids     Orion         10  northern, southern 2020-10-02 2020-11-07
3      Perseids   Perseus          8            northern 2020-07-14 2020-08-24
4       Leonids       Leo         11  northern, southern 2020-11-06 2020-11-30

In [103]:
moon_phases

          date  percentage
0   2020-01-01         NaN
1   2020-01-02         0.5
2   2020-01-03         NaN
3   2020-01-04         NaN
4   2020-01-05         NaN
..         ...         ...
361 2020-12-27         NaN
362 2020-12-28         NaN
363 2020-12-29         NaN
364 2020-12-30         NaN
365 2020-12-31         NaN

[366 rows x 2 columns]

In [110]:
moon_phases

          date  percentage
0   2020-01-01         NaN
1   2020-01-02         0.5
2   2020-01-03         NaN
3   2020-01-04         NaN
4   2020-01-05         NaN
..         ...         ...
361 2020-12-27         NaN
362 2020-12-28         NaN
363 2020-12-29         NaN
364 2020-12-30         NaN
365 2020-12-31         NaN

[366 rows x 2 columns]

## 달의 위상 누락값 처리

In [127]:
#ffill, bfill
#moon_phases['percentage'].ffill()
moon_phases['percentage'] = moon_phases['percentage'].ffill().fillna(0)
#moon_phases.head(10)

In [128]:
moon_phases

          date  percentage
0   2020-01-01         0.0
1   2020-01-02         0.5
2   2020-01-03         0.5
3   2020-01-04         0.5
4   2020-01-05         0.5
..         ...         ...
361 2020-12-27         0.5
362 2020-12-28         0.5
363 2020-12-29         1.0
364 2020-12-30         1.0
365 2020-12-31         1.0

[366 rows x 2 columns]

## 데이터분석

## 위도 조회

In [ ]:
# 도시 데이터프레임에서 검색한 열(검색한 도시의 위도)만 가져오기
# dframe.loc[조건, 가져올 컬럼 이름]

In [130]:
cities

                        city  latitude               country
0                  Abu Dhabi     24.47  United Arab Emirates
1                      Abuja      9.07               Nigeria
2                      Accra      5.55                 Ghana
3                  Adamstown    -25.07      Pitcairn Islands
4                Addis Ababa      9.02              Ethiopia
..                       ...       ...                   ...
251  Abidjan(former capital)      6.82           Ivory Coast
252                  Yaounde      3.87              Cameroon
253          Yaren(de facto)     -0.53                 Nauru
254                  Yerevan     40.18               Armenia
255                   Zagreb     45.82               Croatia

[256 rows x 3 columns]

In [169]:
# 도시명을 입력하면 위도를 반환하는 함수 만들기

def predict_best_meteor_shower_viewing(x):
    latitude = cities.loc[cities['city'] == x,'latitude'].iloc[0]
    return latitude

In [159]:
cities.loc[cities['city'] == 'Abu Dhabi','latitude']

0    24.47
Name: latitude, dtype: float64

In [172]:
print(predict_best_meteor_shower_viewing('Wellington'))

-41.28

## 특정 위도에서 볼 수 있는 별자리 조회

In [207]:
# 도시명을 입력하면 위도와 별자리 리스트를 반환하는 함수
def predict_best_meteor_shower_viewing(x):
    # 입력된 도시의 위조 정보 조회
    latitude = cities.loc[cities['city'] == x,'latitude'].iloc[0]
    # 반환된 위도에서 관측가능한 별자리 조회
    constell = constellations.loc[(constellations['latitudestart'] >= latitude) & (constellations['latitudeend'] <= latitude),['constellation']].values
    return latitude, constell

In [209]:
def predict_best_meteor_shower_viewing(city_name):
    
    latitude = cities.loc[cities['city'] == city_name, 'latitude'].iloc[0]
    
    
    constellation_list = constellations.loc[
        (constellations['latitudestart'] >= latitude) & 
        (constellations['latitudeend'] <= latitude), 
        'constellation'].tolist() 
    
    
    return latitude, constellation_list

In [205]:
a= -41.28
constellations.loc[(constellations['latitudestart'] >= a) & (constellations['latitudeend'] <= a),['constellation']].values.tolist()

[['Aquarius'], ['Orion']]

In [210]:
print(predict_best_meteor_shower_viewing('Wellington'))

(np.float64(-41.28), ['Aquarius', 'Orion'])

In [171]:
constellations

  constellation  bestmonth  latitudestart  latitudeend hemisphere
0          Lyra          8             90          -40   northern
1      Aquarius         10             65          -90   southern
2         Orion          1             85          -75   northern
3       Perseus         12             90          -35   northern
4           Leo          4             90           65   northern

In [257]:
def predict_best_meteor_shower_viewing(city_name):
    
    if city_name not in cities['city'].values:
        temp =  f'{city_name}에서 서비스 할 수 없습니다.'
        return temp
    latitude = cities.loc[cities['city'] == city_name, 'latitude'].iloc[0]

    constellation_list = constellations.loc[
        (constellations['latitudestart'] >= latitude) & 
        (constellations['latitudeend'] <= latitude), 
        'constellation'].tolist() 
    
    if constellation_list == []:
       result =  f'{city_name}에서는 관측할 수 없습니다.'
    else:
       result =  f'{city_name}에서 별자리 관측이 가능합니다.'
    
    return latitude, constellation_list, result

In [258]:
print(predict_best_meteor_shower_viewing('Wellington'))

(np.float64(-41.28), ['Aquarius', 'Orion'], 'Wellington에서 별자리 관측이 가능합니다.')

In [260]:
print(predict_best_meteor_shower_viewing('Busan'))

Busan에서 서비스 할 수 없습니다.

In [261]:
constellations

  constellation  bestmonth  latitudestart  latitudeend hemisphere
0          Lyra          8             90          -40   northern
1      Aquarius         10             65          -90   southern
2         Orion          1             85          -75   northern
3       Perseus         12             90          -35   northern
4           Leo          4             90           65   northern

In [262]:
meteor_showers

           name   radiant  bestmonth          hemisphere  startdate    enddate
0        Lyrids      Lyra          4            northern 2020-04-21 2020-04-22
1  Eta Aquarids  Aquarius          5  northern, southern 2020-04-19 2020-05-28
2      Orionids     Orion         10  northern, southern 2020-10-02 2020-11-07
3      Perseids   Perseus          8            northern 2020-07-14 2020-08-24
4       Leonids       Leo         11  northern, southern 2020-11-06 2020-11-30

In [263]:
constellations['constellation']

0        Lyra
1    Aquarius
2       Orion
3     Perseus
4         Leo
Name: constellation, dtype: str

In [382]:
def predict_best_meteor_shower_viewing(city_name):
    
    if city_name not in cities['city'].values:
        temp =  f'{city_name}에서 서비스 할 수 없습니다.'
        return temp
    latitude = cities.loc[cities['city'] == city_name, 'latitude'].iloc[0]

    constellation_list = constellations.loc[
        (constellations['latitudestart'] >= latitude) & 
        (constellations['latitudeend'] <= latitude), 
        'constellation'].tolist() 
    
    if constellation_list == []:
       result =  f'{city_name}에서는 관측할 수 없습니다.'
       return result
    else:
       result =  f'{city_name}에서 별자리 관측이 가능합니다.\n'
    
    #print(result)

    for i in constellation_list:
        meteor_shower = meteor_showers.loc[meteor_showers['radiant']==i,'name',].iloc[0]
        meteor_shower_startdate = meteor_showers.loc[meteor_showers['radiant']==i,'startdate',].iloc[0]#.to_pydatetime().strftime('%Y년 %m월 %d일')
        meteor_shower_enddate = meteor_showers.loc[meteor_showers['radiant']==i,'enddate',].iloc[0]#.to_pydatetime().strftime('%Y년 %m월 %d일')
        #print(meteor_shower, meteor_shower_startdate, meteor_shower_enddate)

        moon_phase_list = moon_phases.loc[(moon_phases['date'] >= meteor_shower_startdate) & (moon_phases['date'] <= meteor_shower_enddate)]
        moon_phase_list['percentage'].idxmin()
        best_moon_date = moon_phase_list.loc[moon_phase_list['percentage'].idxmin()]['date'].to_pydatetime().strftime('%Y년 %m월 %d일')
        result += f'{meteor_shower} 유성우를 잘보려면 {i}자리 위치를 향하여 {best_moon_date}보면 됩니다.\n'

    return result

In [383]:
print(predict_best_meteor_shower_viewing('Wellington'))

Wellington에서 별자리 관측이 가능합니다.
Eta Aquarids 유성우를 잘보려면 Aquarius자리 위치를 향하여 2020년 04월 22일보면 됩니다.
Orionids 유성우를 잘보려면 Orion자리 위치를 향하여 2020년 10월 16일보면 됩니다.

In [384]:
print(predict_best_meteor_shower_viewing('Seoul'))

Seoul에서 별자리 관측이 가능합니다.
Lyrids 유성우를 잘보려면 Lyra자리 위치를 향하여 2020년 04월 22일보면 됩니다.
Eta Aquarids 유성우를 잘보려면 Aquarius자리 위치를 향하여 2020년 04월 22일보면 됩니다.
Orionids 유성우를 잘보려면 Orion자리 위치를 향하여 2020년 10월 16일보면 됩니다.
Perseids 유성우를 잘보려면 Perseus자리 위치를 향하여 2020년 07월 20일보면 됩니다.

In [385]:
print(predict_best_meteor_shower_viewing('Busan'))

Busan에서 서비스 할 수 없습니다.

In [268]:
clist=['Orion']

In [279]:
name = meteor_showers.loc[meteor_showers['radiant'].isin(clist),'name',].iloc[0]

In [280]:
print(name)

Orionids

In [294]:
for i in ['Lyra','Aquarius','Orion','Perseus']:
        meteor_shower = meteor_showers.loc[meteor_showers['radiant']==i,'name',].iloc[0]
        meteor_shower_startdate = meteor_showers.loc[meteor_showers['radiant']==i,'startdate',].iloc[0]
        meteor_shower_enddate = meteor_showers.loc[meteor_showers['radiant']==i,'enddate',].iloc[0]
        print(meteor_shower, meteor_shower_startdate, meteor_shower_enddate)

Lyrids 2020-04-21 00:00:00 2020-04-22 00:00:00
Eta Aquarids 2020-04-19 00:00:00 2020-05-28 00:00:00
Orionids 2020-10-02 00:00:00 2020-11-07 00:00:00
Perseids 2020-07-14 00:00:00 2020-08-24 00:00:00

In [301]:
meteor_shower_startdate.to_pydatetime().strftime('%Y년 %m월 %d일')

'2020년 07월 14일'

In [310]:
moon_phase_list = moon_phases.loc[(moon_phases['date'] >= meteor_shower_startdate) & (moon_phases['date'] <= meteor_shower_enddate)]
moon_phase_list.head()

          date  percentage
195 2020-07-14         0.5
196 2020-07-15         0.5
197 2020-07-16         0.5
198 2020-07-17         0.5
199 2020-07-18         0.5

In [311]:
moon_phase_list['percentage'].idxmin()

201

In [312]:
best_moon_date = moon_phase_list.loc[moon_phase_list['percentage'].idxmin()]['date']
best_moon_date

Timestamp('2020-07-20 00:00:00')

In [ ]:
def predict_best_meteor_shower_viewing(city_name):
    
    if city_name not in cities['city'].values:
        temp =  f'{city_name}에서 서비스 할 수 없습니다.'
        return temp
    latitude = cities.loc[cities['city'] == city_name, 'latitude'].iloc[0]

    constellation_list = constellations.loc[
        (constellations['latitudestart'] >= latitude) & 
        (constellations['latitudeend'] <= latitude), 
        'constellation'].tolist() 
    
    if constellation_list == []:
       result =  f'{city_name}에서는 관측할 수 없습니다.'
       return result
    else:
       result =  f'{city_name}에서 별자리 관측이 가능합니다.\n'
    
    #print(result)

    for i in constellation_list:
        meteor_shower = meteor_showers.loc[meteor_showers['radiant']==i,'name',].iloc[0]
        meteor_shower_startdate = meteor_showers.loc[meteor_showers['radiant']==i,'startdate',].iloc[0]#.to_pydatetime().strftime('%Y년 %m월 %d일')
        meteor_shower_enddate = meteor_showers.loc[meteor_showers['radiant']==i,'enddate',].iloc[0]#.to_pydatetime().strftime('%Y년 %m월 %d일')
        #print(meteor_shower, meteor_shower_startdate, meteor_shower_enddate)

        moon_phase_list = moon_phases.loc[(moon_phases['date'] >= meteor_shower_startdate) & (moon_phases['date'] <= meteor_shower_enddate)]
        moon_phase_list['percentage'].idxmin()
        best_moon_date = moon_phase_list.loc[moon_phase_list['percentage'].idxmin()]['date'].to_pydatetime().strftime('%Y년 %m월 %d일')
        result += f'{meteor_shower} 유성우를 잘보려면 {i}자리 위치를 향하여 {best_moon_date}보면 됩니다.\n'

    return result

In [386]:
# 항아 유성우 데이터 추가
change_meteor_shower = {'name' : "Chang\'e", 'radiant' : 'Draco', 'bestmonth' : 'october', 'startmonth': 'october', 'startday' : 1,
                        'endmonth' : 'october', 'endday' : 31, 'hemisphere' : 'northern', 'preferredhemisphere' : 'northern' }
change_meteor_shower_df = pd.DataFrame(change_meteor_shower,index = [0])
change_meteor_shower_df

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Chang'e,Draco,october,october,1,october,31,northern,northern

In [402]:
new_meteor_showers = pd.read_csv('pyhon/data/meteorshowers.csv')
new_meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,april,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,may,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,october,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,august,july,14,august,24,northern,northern
4,Leonids,Leo,november,november,6,november,30,"northern, southern","northern, southern"

In [403]:
new_meteor_showers = pd.concat([new_meteor_showers, change_meteor_shower_df],ignore_index=True)

In [404]:
new_meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,april,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,may,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,october,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,august,july,14,august,24,northern,northern
4,Leonids,Leo,november,november,6,november,30,"northern, southern","northern, southern"
5,Chang'e,Draco,october,october,1,october,31,northern,northern

In [405]:
new_meteor_showers['bestmonth'] = new_meteor_showers['bestmonth'].map(months)
new_meteor_showers['startmonth'] = new_meteor_showers['startmonth'].map(months)
new_meteor_showers['endmonth'] = new_meteor_showers['endmonth'].map(months)

In [407]:
new_meteor_showers['startdate'] = pd.to_datetime(2020*10000 + new_meteor_showers['startmonth']*100 + new_meteor_showers['startday'],format='%Y%m%d')

In [409]:
new_meteor_showers['enddate'] = pd.to_datetime(2020*10000 + new_meteor_showers['endmonth']*100 + new_meteor_showers['endday'],format='%Y%m%d')

In [411]:
new_meteor_showers.drop(columns=['startmonth'], inplace=True)
new_meteor_showers.drop(columns=['startday'], inplace=True)
new_meteor_showers.drop(columns=['endmonth'], inplace=True)
new_meteor_showers.drop(columns=['endday'], inplace=True)
new_meteor_showers.drop(columns=['preferredhemisphere'],inplace=True)

In [424]:
new_meteor_showers

           name   radiant  bestmonth          hemisphere  startdate    enddate
0        Lyrids      Lyra          4            northern 2020-04-21 2020-04-22
1  Eta Aquarids  Aquarius          5  northern, southern 2020-04-19 2020-05-28
2      Orionids     Orion         10  northern, southern 2020-10-02 2020-11-07
3      Perseids   Perseus          8            northern 2020-07-14 2020-08-24
4       Leonids       Leo         11  northern, southern 2020-11-06 2020-11-30
5       Chang'e     Draco         10            northern 2020-10-01 2020-10-31

In [429]:
draco_constellation = {'constellation' : 'Draco', 'bestmonth' : 'july', 'latitudestart' : 90, 'latitudeend' : -15, 'besttime' :2100, 'hemisphere' : 'northern'}
draco_constellation_df = pd.DataFrame(draco_constellation, index = [0])
draco_constellation_df

  constellation bestmonth  latitudestart  latitudeend  besttime hemisphere
0         Draco      july             90          -15      2100   northern

In [432]:
draco_constellation_df.drop(columns=['besttime'])

  constellation bestmonth  latitudestart  latitudeend hemisphere
0         Draco      july             90          -15   northern

In [433]:
new_constellations = pd.concat([constellations,draco_constellation_df],ignore_index=True)

In [434]:
new_constellations

  constellation bestmonth  latitudestart  latitudeend hemisphere  besttime
0          Lyra         8             90          -40   northern       NaN
1      Aquarius        10             65          -90   southern       NaN
2         Orion         1             85          -75   northern       NaN
3       Perseus        12             90          -35   northern       NaN
4           Leo         4             90           65   northern       NaN
5         Draco      july             90          -15   northern    2100.0

In [437]:
def predict_best_meteor_shower_viewing(city_name):
    
    if city_name not in cities['city'].values:
        temp =  f'{city_name}에서 서비스 할 수 없습니다.'
        return temp
    latitude = cities.loc[cities['city'] == city_name, 'latitude'].iloc[0]

    constellation_list = new_constellations.loc[
        (new_constellations['latitudestart'] >= latitude) & 
        (new_constellations['latitudeend'] <= latitude), 
        'constellation'].tolist() 
    
    if constellation_list == []:
       result =  f'{city_name}에서는 관측할 수 없습니다.'
       return result
    else:
       result =  f'{city_name}에서 별자리 관측이 가능합니다.\n'
    
    #print(result)

    for i in constellation_list:
        meteor_shower = new_meteor_showers.loc[new_meteor_showers['radiant']==i,'name',].iloc[0]
        meteor_shower_startdate = new_meteor_showers.loc[new_meteor_showers['radiant']==i,'startdate',].iloc[0]#.to_pydatetime().strftime('%Y년 %m월 %d일')
        meteor_shower_enddate = new_meteor_showers.loc[new_meteor_showers['radiant']==i,'enddate',].iloc[0]#.to_pydatetime().strftime('%Y년 %m월 %d일')
        #print(meteor_shower, meteor_shower_startdate, meteor_shower_enddate)

        moon_phase_list = moon_phases.loc[(moon_phases['date'] >= meteor_shower_startdate) & (moon_phases['date'] <= meteor_shower_enddate)]
        moon_phase_list['percentage'].idxmin()
        best_moon_date = moon_phase_list.loc[moon_phase_list['percentage'].idxmin()]['date'].to_pydatetime().strftime('%Y년 %m월 %d일')
        result += f'{meteor_shower} 유성우를 잘 보려면 {i}자리 위치를 향하여 {best_moon_date}에 관측하면 됩니다.\n'

    return result

In [438]:
print(predict_best_meteor_shower_viewing('Beijing'))

Beijing에서 별자리 관측이 가능합니다.
Lyrids 유성우를 잘 보려면 Lyra자리 위치를 향하여 2020년 04월 22일에 관측하면 됩니다.
Eta Aquarids 유성우를 잘 보려면 Aquarius자리 위치를 향하여 2020년 04월 22일에 관측하면 됩니다.
Orionids 유성우를 잘 보려면 Orion자리 위치를 향하여 2020년 10월 16일에 관측하면 됩니다.
Perseids 유성우를 잘 보려면 Perseus자리 위치를 향하여 2020년 07월 20일에 관측하면 됩니다.
Chang'e 유성우를 잘 보려면 Draco자리 위치를 향하여 2020년 10월 16일에 관측하면 됩니다.